#!/usr/bin/env bash
# This script is displaying with a loop that displays
# bad luck for the 4th loop iteration
# good luck for the 8th loop iteration
# Holberton School for the other iterations
i=0
while [ $i -le 9 ];
do
  if [ $i -eq 3 ]
  then
      echo "bad luck"
      elif [ $i -eq 7 ]
      then
      echo "good luck"
      else
      echo "Holberton School"
      fi
      ((i++))
done
