#!/usr/bin/env bash
# This script that displays To infinity and beyond indefinitely
# with a sleep 2 in between each iteration
# and I am invincible!!! when receiving a SIGTERM signal
i=1
trap "echo I am invincible!!!" 15
while (( i > 0 ))
do
  echo "To infinity and beyond"
  sleep 2
done
